import DebitNoteNumberNormalizer from '../DebitNoteNumberNormalizer.js'

/**
 * One way of deciding which cover-sheet row a debit note belongs to (`ENG-02` `ADR-10`).
 *
 * **The piece the PoC keeps replaceable.** This version covers 1:1 submissions only; supporting one
 * debit note against several approval PDFs is meant to arrive as another subclass rather than as a
 * rewrite of check ③, which is the whole reason matching is a strategy and not an `if` inside the
 * amount comparison (`ADR-10`).
 *
 * A strategy **collects candidates and never chooses between them**. Answering with two rows is a
 * legitimate answer, and `CoverSheetRowMatcher` turns it into `NG-006`: a silently wrong pairing
 * produces a confident wrong judgment, which is worse than an explicit NG (`FR-037`).
 *
 * **Every rule compares normalized keys** (`FR-038`). The sheet writes `HIB-002/YEVMP26-003` and the
 * subsidiary names the file `HIB-002YEVMP26-003.pdf`, so the separators are decoration on one side
 * and absent on the other - two documents that are the same document. Normalizing is what the base
 * class contributes, so a rule added later cannot forget to do it and match on a verbatim form that
 * only ever agrees by luck.
 *
 * @abstract
 */
export default class BaseCoverSheetRowMatchStrategy {
  /**
   * Constructor.
   *
   * @param {{
   *   debitNoteNumber: string | null
   *   coverSheetRows: Array<verification.ComparedCoverSheetRow>
   *   fileName: string
   * }} params - Parameters of this constructor.
   */
  constructor ({
    debitNoteNumber,
    coverSheetRows,
    fileName,
  }) {
    this.debitNoteNumber = debitNoteNumber
    this.coverSheetRows = coverSheetRows
    this.fileName = fileName
  }

  /**
   * Factory method.
   *
   * @param {{
   *   debitNoteNumber: string | null
   *   coverSheetRows: Array<verification.ComparedCoverSheetRow>
   *   fileName: string
   * }} params - Parameters of this method.
   * @returns {BaseCoverSheetRowMatchStrategy} - Instance of this class.
   */
  static create (params) {
    return new this(params)
  }

  /**
   * Collect every cover-sheet row this strategy considers a match.
   *
   * @abstract
   * @returns {Array<verification.ComparedCoverSheetRow>} - The candidates, possibly none or several.
   * @throws {Error} - this function must be inherited
   */
  collectMatchedRows () {
    throw new Error('this function must be inherited')
  }

  /**
   * Collect the rows carrying a matching key at all.
   *
   * **An empty key matches nothing rather than everything.** A number written as nothing but
   * separators normalizes away to `''`, which every comparison a rule could make would accept - so
   * the row that lost its key would be a candidate for every debit note of the batch (`FR-037`).
   *
   * @returns {Array<verification.ComparedCoverSheetRow>} - The rows a rule may compare against.
   */
  collectKeyedRows () {
    return this.coverSheetRows
      .filter(coverSheetRow => coverSheetRow.normalizedDebitNoteNumber !== '')
  }

  /**
   * Generate one value in the form the rules compare (`FR-038`).
   *
   * @param {{
   *   debitNoteNumber: string
   * }} params - Parameters of this method.
   * @returns {string} - The key.
   */
  generateNormalizedNumber ({
    debitNoteNumber,
  }) {
    return this.createDebitNoteNumberNormalizer({
      debitNoteNumber,
    })
      .generateNormalizedNumber()
  }

  /**
   * Create the normalizer a key is generated by.
   *
   * @param {{
   *   debitNoteNumber: string
   * }} params - Parameters of this method.
   * @returns {DebitNoteNumberNormalizer} - The normalizer.
   */
  createDebitNoteNumberNormalizer ({
    debitNoteNumber,
  }) {
    return DebitNoteNumberNormalizer.create({
      debitNoteNumber,
    })
  }
}
